name: "fast-bird"

services:
  entry:
    image: nginx:1.27.1-alpine
    init: true
    secrets:
      - source: blldxt91fy_fullchain
        target: /run/secrets/grayless_fullchain.pem
      - source: blldxt91fy_privkey
        target: /run/secrets/grayless_privkey.pem
    configs:
      - source: nginx_frps
        target: /etc/nginx/templates/blldxt91fy.frps.conf.template
    ports:
      - "80:80"
      - "443:443"
  frps:
    image: fast_bird_frps
    hostname: top.grayless.frps
    build:
      target: frps
    init: true
    tty: true
    configs:
      - source: frps
        target: /etc/frps.toml
    expose:
      - 7000
      - 7500
      - 5002
      - 8082
    ports:
      - "7000:7000"

configs:
  frps:
    file: config/frp/frps.toml
  nginx_frps:
    file: config/entry/conf.d/blldxt91fy.frps.conf

secrets:
  blldxt91fy_fullchain:
    file: /etc/letsencrypt/live/grayless.top/fullchain.pem
  blldxt91fy_privkey:
    file: /etc/letsencrypt/live/grayless.top/privkey.pem
